# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ADOScheduledWorkItemQuery@0
  inputs:
    sendMethod: 'SendGrid'
    connectedServiceNameSendGrid: 'devops monitor'
    project: '622191f2-3ad3-49e0-b0fc-8ad84f8281ff'
    queryType: 'Shared'
    query: 'f417cf2c-73d1-40f6-b10b-f74bd2229438'
    sendIfEmpty: true
    subject: 'DevOps Escalation Age Monitor - Results'
    emailAddresses: 'athompson@parata.com,tkriete@parata.com,smarie@parata.com'